# List of WS methods to whitelist.
ws_method_whitelist = [
  "eth_getBlockRange",
  "rollup_getInfo",
  "rollup_gasPrices",
  "web3_clientVersion",
  "web3_sha3",
  "net_version",
  "net_listening",
  "net_peerCount",
  "eth_protocolVersion",
  "eth_syncing",
  "eth_coinbase",
  "eth_mining",
  "eth_hashrate",
  "eth_gasPrice",
  "eth_accounts",
  "eth_blockNumber",
  "eth_getBalance",
  "eth_getStorageAt",
  "eth_getTransactionCount",
  "eth_getBlockTransactionCountByHash",
  "eth_getBlockTransactionCountByNumber",
  "eth_getUncleCountByBlockHash",
  "eth_getUncleCountByBlockNumber",
  "eth_getCode",
  "eth_sign",
  "eth_signTransaction",
  "eth_sendRawTransaction",
  "eth_call",
  "eth_estimateGas",
  "eth_getBlockByHash",
  "eth_getBlockByNumber",
  "eth_getTransactionByHash",
  "eth_getTransactionByBlockHashAndIndex",
  "eth_getTransactionByBlockNumberAndIndex",
  "eth_getTransactionReceipt",
  "eth_getUncleByBlockHashAndIndex",
  "eth_getUncleByBlockNumberAndIndex",
  "eth_getCompilers",
  "eth_compileSolidity",
  "eth_compileLLL",
  "eth_compileSerpent",
  "eth_newFilter",
  "eth_newBlockFilter",
  "eth_newPendingTransactionFilter",
  "eth_uninstallFilter",
  "eth_getFilterChanges",
  "eth_getFilterLogs",
  "eth_getLogs",
  "eth_getWork",
  "eth_submitWork",
  "eth_submitHashrate"
]
# Enable WS on this backend group. There can only be one WS-enabled backend group.
ws_backend_group = "main"

[server]
# Host for the proxyd RPC server to listen on.
rpc_host = "0.0.0.0"
# Port for the above.
rpc_port = 10001
# Host for the proxyd WS server to listen on.
ws_host = "0.0.0.0"
# Port for the above
ws_port = 10002
# Maximum client body size, in bytes, that the server will accept.
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000


[metrics]
# Whether or not to enable Prometheus metrics.
enabled = true
# Host for the Prometheus metrics endpoint to listen on.
host = "0.0.0.0"
# Port for the above.
port = 9761

[backend]
# How long proxyd should wait for a backend response before timing out.
response_timeout_seconds = 5
# Maximum response size, in bytes, that proxyd will accept from a backend.
max_response_size_bytes = 5242880
# Maximum number of times proxyd will try a backend before giving up.
max_retries = 3
# Number of seconds to wait before trying an unhealthy backend again.
out_of_service_seconds = 600

[backends]
# A map of backends by name.
[backends.l2geth]
# The URL to contact the backend at. Will be read from the environment
# if an environment variable prefixed with $ is provided.
rpc_url = "$L2GETH_HTTP_PORT"
# The WS URL to contact the backend at. Will be read from the environment
# if an environment variable prefixed with $ is provided.
ws_url = "$L2GETH_WS_PORT"
username = ""
# An HTTP Basic password to authenticate with the backend. Will be read from
# the environment if an environment variable prefixed with $ is provided.
password = ""
max_rps = 3
max_ws_conns = 1
# Path to a custom root CA.
ca_file = ""
# Path to a custom client cert file.
client_cert_file = ""
# Path to a custom client key file.
client_key_file = ""


[backend_groups]
[backend_groups.main]
backends = ["l2geth"]

# Mapping of methods to backend groups.
[rpc_method_mappings]
eth_getBlockRange = "main"
rollup_getInfo = "main"
rollup_gasPrices = "main"
web3_clientVersion = "main"
web3_sha3 = "main"
net_version = "main"
net_listening = "main"
net_peerCount = "main"
eth_protocolVersion = "main"
eth_syncing = "main"
eth_coinbase = "main"
eth_mining = "main"
eth_hashrate = "main"
eth_gasPrice = "main"
eth_accounts = "main"
eth_blockNumber = "main"
eth_getBalance = "main"
eth_getStorageAt = "main"
eth_getTransactionCount = "main"
eth_getBlockTransactionCountByHash = "main"
eth_getBlockTransactionCountByNumber = "main"
eth_getUncleCountByBlockHash = "main"
eth_getUncleCountByBlockNumber = "main"
eth_getCode = "main"
eth_sign = "main"
eth_signTransaction = "main"
eth_sendRawTransaction = "main"
eth_call = "main"
eth_estimateGas = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getTransactionByHash = "main"
eth_getTransactionByBlockHashAndIndex = "main"
eth_getTransactionByBlockNumberAndIndex = "main"
eth_getTransactionReceipt = "main"
eth_getUncleByBlockHashAndIndex = "main"
eth_getUncleByBlockNumberAndIndex = "main"
eth_getCompilers = "main"
eth_compileSolidity = "main"
eth_compileLLL = "main"
eth_compileSerpent = "main"
eth_newFilter = "main"
eth_newBlockFilter = "main"
eth_newPendingTransactionFilter = "main"
eth_uninstallFilter = "main"
eth_getFilterChanges = "main"
eth_getFilterLogs = "main"
eth_getLogs = "main"
eth_getWork = "main"
eth_submitWork = "main"
eth_submitHashrate = "main"
