apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-hardhat.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: integration-tests
  name: integration-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: integration-tests
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-hardhat.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: integration-tests
    spec:
      containers:
      - command:
        # Command doesn't do anything; integration tests can be run using constellation-integration-tests.sh.
        - sleep
        - infinity
        envFrom:
          - configMapRef:
              name: envs-system-addr-env
        env:
        - name: L1_URL
          valueFrom:
            configMapKeyRef:
              key: L1_RPC_URL
              name: envs-main-env
        - name: L2_URL
          value: "http://l2geth:8545"
        - name: HEALTHCHECK_URL
          value: "http://replica_healthcheck:7300/metrics"
        - name: REPLICA_URL
          value: "http://replica:8545"
        - name: VERIFIER_URL
          value: "http://verifier:8545"
        - name: URL
          value: "http://deployer:8081/addresses.json"
        - name: ENABLE_GAS_REPORT
          value: "1"
        - name: NO_NETWORK
          value: "1"
        - name: BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE
          valueFrom:
            configMapKeyRef:
              key: BATCH_SUBMITTER_SEQUENCER_BATCH_TYPE
              name: envs-main-env

        - name: RUN_SYSTEM_ADDRESS_TESTS
          value: "false"
        - name: RUN_HEALTHCHECK_TESTS
          value: "false"
        - name: PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: DEPLOYER_PRIVATE_KEY
              name: envs-main-env
        - name: L2_CHAINID
          valueFrom:
            configMapKeyRef:
              key: L2_CHAIN_ID
              name: envs-main-env
        - name: GAS_PRICE_ORACLE_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: GAS_PRICE_ORACLE_OWNER_PRIVATE_KEY
              name: envs-main-env
        - name: TEST_FPE
          valueFrom:
            configMapKeyRef:
              key: TEST_FPE
              name: envs-main-env
        image: ethereumoptimism/integration-tests:latest
        imagePullPolicy: Never
        name: integration-tests
        resources:
          requests:
            memory: "1000Mi"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
