name: Code Coverage

on:
  workflow_dispatch:

jobs:
  test-coverage:
    name: Generate test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test Coverage
        run: yarn test:coverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/contracts/coverage.json
          fail_ci_if_error: true
          verbose: true
          flags: contracts
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/core-utils/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: core-utils
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/data-transport-layer/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: data-transport-layer
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/message-relayer/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: message-relayer
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/sdk/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: sdk
