name: indexer unit tests

on:
  push:
    paths:
      - 'indexer/**'
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'release/*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

defaults:
  run:
    working-directory: './indexer'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: make

      - name: Test
        run: make test
